import React, { useState } from 'react';

const AFFIRMATIONS = [
  "You are capable of achieving wonderful things today.",
  "Every small step brings you closer to your goals.",
  "Your peace of mind is your top priority.",
  "Believe in your unique strengths and talents.",
  "Today is filled with fresh opportunities and hope.",
  "Give yourself grace; you are doing your absolute best.",
  "Your potential is limitless.",
  "Choose positivity, kindness, and self-compassion.",
  "You radiate energy, confidence, and warmth.",
  "Trust the process of your personal journey.",
  "You are worthy of happiness, love, and success.",
  "Embrace the beauty of starting fresh today.",
  "Your resilience turns challenges into victories.",
  "Focus on progress, not perfection.",
  "You bring light and inspiration to those around you.",
  "Take a deep breath and let go of what you cannot control.",
  "Your efforts today build a better tomorrow.",
  "Celebrate how far you have already come.",
  "You are strong enough to handle any situation.",
  "Kindness to yourself opens doors to happiness.",
  "Today, focus on what truly matters to you.",
  "Your mind is calm, clear, and focused.",
  "You deserve all the good things coming your way.",
  "Every experience helps you grow wiser.",
  "Choose gratitude over worry.",
  "You are enough, exactly as you are right now.",
  "Your hard work will yield amazing results.",
  "Protect your energy and nourish your soul.",
  "Confidence comes from honoring your own path.",
  "Be patient with your growth.",
  "You possess the wisdom to make great decisions.",
  "Let your courage outshine your fears today.",
  "You are creating a life you truly love.",
  "Smile—you are making a difference.",
  "Your positive attitude attracts wonderful opportunities.",
  "Nourish your body, mind, and spirit today.",
  "You are allowed to take breaks and recharge.",
  "Great things take time; keep believing.",
  "Your voice and your feelings matter.",
  "Focus on the present moment.",
  "You are a reflection of strength and grace.",
  "Good things are unfolding around you right now.",
  "Forgive yourself for past mistakes and move forward.",
  "You inspire others simply by being authentic.",
  "Every day offers a fresh, clean slate.",
  "Your heart is open to joy and laughter.",
  "You have the courage to conquer any obstacle.",
  "Happiness starts from within yourself.",
  "Trust that things are working out for your good.",
  "You deserve rest just as much as success.",
  "Your determination creates lasting success.",
  "Welcome new opportunities with open arms.",
  "You are stronger than any difficulty you face.",
  "Choose joy in the simple moments today.",
  "Your journey is unique—embrace every part of it.",
  "Be proud of the progress you make every day.",
  "You attract peace, positivity, and abundance.",
  "Listen to your intuition; it guides you well.",
  "You are capable of extraordinary growth.",
  "Release doubt and embrace confidence.",
  "Today is a new chance to shine.",
  "Your kindness creates a ripple of positivity.",
  "Stay focused on what brings you fulfillment.",
  "You have the power to shape your own future.",
  "Surrender your worries and welcome serenity.",
  "You are worthy of respect and admiration.",
  "Small wins pave the road to massive success.",
  "Your heart is filled with hope and courage.",
  "Embrace change with a positive mindset.",
  "You deserve to feel peaceful and content.",
  "Your dedication will pay off in incredible ways.",
  "You bring warmth and comfort to those around you.",
  "Trust in your ability to learn and adapt.",
  "Your energy is valuable; spend it wisely.",
  "You are deserving of all your dreams.",
  "Every day is an opportunity to learn something new.",
  "You are in charge of your own happiness.",
  "Focus on solutions, not problems.",
  "Your perseverance is your superpower.",
  "You are surrounded by beauty and positivity.",
  "Believe in your dreams even when others doubt.",
  "Take pride in how resilient you are.",
  "Your presence makes the world a warmer place.",
  "Allow yourself to feel happy today.",
  "You are making progress even when it feels slow.",
  "Your intuition leads you in the right direction.",
  "Honor your boundaries and protect your peace.",
  "Today is full of promise and beauty.",
  "You are worthy of unconditional love.",
  "Transform negative energy into positive action.",
  "You have everything you need within you.",
  "Be gentle with your heart today.",
  "Your focus determines your reality.",
  "Choose hope over uncertainty.",
  "You are a magnet for wonderful moments.",
  "Your dreams are worth striving for.",
  "Celebrate your individuality.",
  "You are capable of overcoming any fear.",
  "Your strength inspires those around you.",
  "Take time to appreciate where you are right now.",
  "You are destined for greatness.",
  "Every step forward is a victory.",
  "Your life is full of purpose and meaning.",
  "Choose calm amidst any storm.",
  "You are worthy of taking up space.",
  "Your heart is resilient and full of love.",
  "Confidence grows every time you try.",
  "Focus on what brings you joy today.",
  "You have the wisdom to solve any problem.",
  "Today is a gift; make the most of it.",
  "You attract genuine and supportive people.",
  "Your creative ideas are worth sharing.",
  "Resting is a form of self-love.",
  "You are building a bright and beautiful future.",
  "Choose kindness toward yourself and others.",
  "Your courage is stronger than your comfort zone.",
  "You are worthy of all good things.",
  "Trust your timing—everything happens when it should.",
  "Your potential expands with every effort.",
  "Embrace your strengths and honor your flaws.",
  "You bring light into every room you enter.",
  "Your thoughts shape your world; choose good ones.",
  "You are deserving of peace and clarity.",
  "Be proud of who you are becoming.",
  "Your optimism opens new doors.",
  "You are fully capable of achieving peace.",
  "Every day offers a reason to smile.",
  "Your passion drives your success.",
  "Trust yourself to handle whatever happens.",
  "You are safe, grounded, and secure.",
  "Your journey is leading to great places.",
  "Release what no longer serves your wellbeing.",
  "You are capable of doing hard things.",
  "Your heart is a sanctuary of peace.",
  "Choose joy and let it brighten your day.",
  "You inspire others by staying true to yourself.",
  "Your worth is not defined by productivity.",
  "You are a blessing to those around you.",
  "Focus on creating beauty in your life.",
  "Your inner strength is boundless.",
  "Believe in the power of fresh starts.",
  "You deserve to feel appreciated.",
  "Your dedication inspires excellence.",
  "Choose love over fear in every decision.",
  "You are navigating life with grace.",
  "Your presence brings peace to others.",
  "Celebrate every victory, no matter how small.",
  "You are worthy of fulfillment and success.",
  "Your mind is filled with helpful thoughts.",
  "Trust in your path and stay consistent.",
  "You are capable of achieving inner peace.",
  "Your heart is full of gratitude today.",
  "Embrace the beauty of the present moment.",
  "You bring value wherever you go.",
  "Your energy is magnetic and positive.",
  "Choose to see the good in every situation.",
  "You are worthy of patience and understanding.",
  "Your courage allows you to bloom.",
  "Believe in the power of your dreams.",
  "You are creating a wonderful life story.",
  "Your resilience helps you rise above challenges.",
  "Focus on what you can control.",
  "You are deserving of kindness and care.",
  "Your passion brings excitement to life.",
  "Trust your journey even during uncertain times.",
  "You are a beacon of hope and strength.",
  "Your heart knows the right way forward.",
  "Choose peace over unnecessary conflict.",
  "You are worthy of respect and honor.",
  "Your positive influence reaches far.",
  "Celebrate the unique person you are.",
  "You have the power to change your perspective.",
  "Your determination guarantees progress.",
  "Embrace the warmth of new beginnings.",
  "You are worthy of deep joy.",
  "Your wisdom grows stronger every day.",
  "Choose to act with confidence today.",
  "You bring harmony wherever you go.",
  "Your efforts are making a difference.",
  "Trust that you are right where you need to be.",
  "You are capable of loving deeply.",
  "Your mind is focused and clear.",
  "Release past regrets and welcome today.",
  "You are worthy of finding true fulfillment.",
  "Your spirit is bright and unbreakable.",
  "Choose to believe in endless possibilities.",
  "You inspire everyone around you.",
  "Your potential is unlocked through action.",
  "Be kind to yourself as you grow.",
  "You are worthy of abundance in all forms.",
  "Your inner light guides you safely.",
  "Focus on building positive habits.",
  "You are strong, brave, and capable.",
  "Your life is filled with purpose.",
  "Choose to radiate happiness today.",
  "You are deserving of every blessing.",
  "Your heart is full of compassion.",
  "Trust that the best is yet to come.",
  "You are building strength every single day.",
  "Your thoughts are aligned with your goals.",
  "Embrace every lesson life offers.",
  "You are worthy of true connection.",
  "Your grace turns challenges into beauty.",
  "Choose to focus on your blessings.",
  "You have the power to create harmony.",
  "Your progress is worth celebrating.",
  "Believe in your ability to succeed.",
  "You are surrounded by support and love.",
  "Your soul is peaceful and quiet.",
  "Choose to make today memorable.",
  "You are capable of turning dreams into reality.",
  "Your kindness touches many lives.",
  "Trust in your capacity to heal and grow.",
  "You are worthy of self-care and rest.",
  "Your enthusiasm brings energy to your work.",
  "Focus on light, love, and positivity.",
  "You are an example of resilience.",
  "Your future is bright and promising.",
  "Choose to let go of perfectionism.",
  "You are deserving of boundless joy.",
  "Your journey is filled with purpose.",
  "Trust yourself to make good choices.",
  "You bring joy into the lives of others.",
  "Your mind is filled with creative ideas.",
  "Embrace every challenge as an opportunity.",
  "You are worthy of feeling safe and valued.",
  "Your strength carries you through any storm.",
  "Choose to smile at life's blessings.",
  "You have the power to start fresh anytime.",
  "Your growth is steady and meaningful.",
  "Believe that good things are coming.",
  "You are worthy of high regard.",
  "Your heart is open to love and healing.",
  "Trust the wisdom of your journey.",
  "You are capable of mastering any skill.",
  "Your positive energy inspires others.",
  "Choose to speak kindly to yourself.",
  "You are deserving of peace in your soul.",
  "Your presence is a wonderful gift.",
  "Focus on creating meaningful moments.",
  "You are strong enough to overcome anything.",
  "Your life is guided by hope and love.",
  "Choose joy as your default mindset.",
  "You are worthy of every happiness.",
  "Your determination overcomes any obstacle.",
  "Trust in the beauty of new starts.",
  "You are capable of creating greatness.",
  "Your spirit is free and vibrant.",
  "Embrace the warmth of love around you.",
  "You are worthy of honor and praise.",
  "Your wisdom guides your path.",
  "Choose to act with courage today.",
  "You bring peace wherever you walk.",
  "Your efforts bring meaningful results.",
  "Trust that your timing is perfect.",
  "You are capable of incredible things.",
  "Your mind is calm, relaxed, and focused.",
  "Release worry and welcome clarity.",
  "You are worthy of finding your purpose.",
  "Your inner strength is unwavering.",
  "Choose to see infinite potential around you.",
  "You inspire those who cross your path.",
  "Your actions lead to great success.",
  "Be patient and gentle with your heart.",
  "You are worthy of living abundantly.",
  "Your light shines brightly today.",
  "Focus on growing a little each day.",
  "You are brave, resilient, and strong.",
  "Your life has deep meaning and value.",
  "Choose to share your smile today.",
  "You are deserving of all good things.",
  "Your heart is full of empathy.",
  "Trust that great things are coming.",
  "You build resilience with every step.",
  "Your mindset is aligned with success.",
  "Embrace every new experience.",
  "You are worthy of deep and genuine joy.",
  "Your grace shines in difficult times.",
  "Choose to count your blessings.",
  "You have the power to bring peace.",
  "Your growth is worthy of praise.",
  "Believe in your infinite potential.",
  "You are supported by positive energy.",
  "Your soul is centered and peaceful.",
  "Choose to make today incredible.",
  "You can turn any vision into reality.",
  "Your kindness makes a real impact.",
  "Trust your ability to bounce back.",
  "You are worthy of taking time for yourself.",
  "Your energy brings life to your dreams.",
  "Focus on gratitude and peace.",
  "You embody strength and perseverance.",
  "Your future is filled with hope.",
  "Choose to accept yourself completely.",
  "You are deserving of pure happiness.",
  "Your journey unfolds perfectly.",
  "Trust yourself; you know the way.",
  "You bring lightness into hard situations.",
  "Your mind is capable of deep focus.",
  "Embrace every obstacle as a stepping stone.",
  "You are worthy of respect and honor.",
  "Your inner strength is remarkable.",
  "Choose to find beauty everywhere.",
  "You can begin again at any moment.",
  "Your steady progress matters.",
  "Believe that miracles happen every day.",
  "You are worthy of self-love.",
  "Your heart is ready for good things.",
  "Trust in the wisdom of experience.",
  "You are capable of great wisdom.",
  "Your vibe attracts positive people.",
  "Choose to speak words of encouragement.",
  "You are deserving of complete peace.",
  "Your life is a beautiful journey.",
  "Focus on what truly brings you joy.",
  "You are tough, capable, and smart.",
  "Your world is full of possibility.",
  "Choose happiness today and always.",
  "You are worthy of celebrating.",
  "Your courage opens doors to success.",
  "Trust in your unique gifts.",
  "You are capable of boundless love.",
  "Your spirit is cheerful and light.",
  "Embrace peace in your heart.",
  "You are worthy of every dream you have.",
  "Your wisdom brings clarity to life.",
  "Choose to live with confidence.",
  "You bring light into the darkest moments.",
  "Your hard work pays off every day.",
  "Trust that your path is unfolding well.",
  "You are capable of doing amazing things.",
  "Your mind is balanced and serene.",
  "Release doubt and embrace hope.",
  "You are worthy of a bright future.",
  "Your resilience turns trial into triumph.",
  "Choose to see the good in yourself.",
  "You inspire others to be better.",
  "Your actions build a better world.",
  "Be kind to your spirit today.",
  "You are worthy of all peace and comfort.",
  "Your light inspires everyone around.",
  "Focus on being your best self.",
  "You are strong, courageous, and bold.",
  "Your purpose is clearer every day.",
  "Choose to spread warmth and joy.",
  "You are deserving of boundless blessings.",
  "Your heart is filled with pure peace.",
  "Trust that wonderful things lie ahead.",
  "You are growing into your best version.",
  "Your positive thoughts create positive outcomes.",
  "Embrace life's journey with excitement.",
  "You are worthy of deep contentment.",
  "Your grace is your quiet strength.",
  "Choose to focus on love and light.",
  "You have the power to inspire change.",
  "Your journey is worth celebrating.",
  "Believe in your power to overcome.",
  "You are loved, valued, and appreciated.",
  "Your soul is at peace today.",
  "Choose to make today unforgettable.",
  "You can achieve anything you set your mind to.",
  "Your kindness shines brightly.",
  "Trust that everything is coming together.",
  "You are worthy of peace, joy, and love."
];

export default function DailyAffirmation() {
  const getDayOfYear = () => {
    const now = new Date();
    const start = new Date(now.getFullYear(), 0, 0);
    const diff = now - start;
    const oneDay = 1000 * 60 * 60 * 24;
    return Math.floor(diff / oneDay) % AFFIRMATIONS.length;
  };

  const [index, setIndex] = useState(getDayOfYear());

  const handleNext = () => {
    setIndex((prev) => (prev + 1) % AFFIRMATIONS.length);
  };

  return (
    <div className="relative overflow-hidden bg-gradient-to-r from-amber-500/10 via-amber-400/5 to-rose-500/10 backdrop-blur-md border border-amber-200/60 rounded-3xl p-5 shadow-sm hover:shadow-md transition-all duration-300">
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <div className="w-9 h-9 rounded-2xl bg-amber-500/15 border border-amber-500/30 flex items-center justify-center text-amber-600 shadow-inner flex-shrink-0">
            ✨
          </div>
          <div>
            <span className="text-[10px] font-bold uppercase tracking-wider text-amber-700/80">
              Daily Affirmation
            </span>
            <p className="text-sm font-medium text-stone-800 leading-snug mt-0.5 italic">
              "{AFFIRMATIONS[index]}"
            </p>
          </div>
        </div>

        <button
          onClick={handleNext}
          title="New Affirmation"
          className="text-stone-400 hover:text-amber-600 hover:bg-amber-100/50 p-2 rounded-xl transition text-xs font-semibold flex-shrink-0"
        >
          🔄
        </button>
      </div>
    </div>
  );
}